### ISSUE TITLE
Include errors under OpenSUSE 15.2 (Clang 11.0.0 RC2)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [cisco/mlspp#105]
Hi.
I was trying to build in the following way:

> ../build/$cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS=' -stdlib=libc++ ' ..
> -- The CXX compiler identification is Clang 11.0.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/clang++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "2.0.0", minimum required is "1.1")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/oceanfish81/mlspp/build

Here is what I got, during execution of 

> $make -j 4 --trace
 : 
> 
> Makefile:578: target 'cmake_check_build_system' does not exist
> /usr/bin/cmake -P /home/oceanfish81/mlspp/build/CMakeFiles/VerifyGlobs.cmake
> /usr/bin/cmake -S/home/oceanfish81/mlspp -B/home/oceanfish81/mlspp/build --check-build-system CMakeFiles/Makefile.cmake 0
> Makefile:102: update target 'all' due to: cmake_check_build_system
> /usr/bin/cmake -E cmake_progress_start /home/oceanfish81/mlspp/build/CMakeFiles /home/oceanfish81/mlspp/build//CMakeFiles/progress.marks
> make -s -f CMakeFiles/Makefile2 all
> CMakeFiles/Makefile2:406: target 'lib/tls_syntax/CMakeFiles/tls_syntax.dir/all' does not exist
> make -s -f lib/tls_syntax/CMakeFiles/tls_syntax.dir/build.make lib/tls_syntax/CMakeFiles/tls_syntax.dir/depend
> CMakeFiles/Makefile2:324: target 'lib/bytes/CMakeFiles/bytes.dir/all' does not exist
> make -s -f lib/bytes/CMakeFiles/bytes.dir/build.make lib/bytes/CMakeFiles/bytes.dir/depend
> lib/tls_syntax/CMakeFiles/tls_syntax.dir/build.make:116: target 'lib/tls_syntax/CMakeFiles/tls_syntax.dir/depend' does not exist
> cd /home/oceanfish81/mlspp/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/oceanfish81/mlspp /home/oceanfish81/mlspp/lib/tls_syntax /home/oceanfish81/mlspp/build /home/oceanfish81/mlspp/build/lib/tls_syntax /home/oceanfish81/mlspp/build/lib/tls_syntax/CMakeFiles/tls_syntax.dir/DependInfo.cmake --color=
> lib/bytes/CMakeFiles/bytes.dir/build.make:116: target 'lib/bytes/CMakeFiles/bytes.dir/depend' does not exist
> cd /home/oceanfish81/mlspp/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/oceanfish81/mlspp /home/oceanfish81/mlspp/lib/bytes /home/oceanfish81/mlspp/build /home/oceanfish81/mlspp/build/lib/bytes /home/oceanfish81/mlspp/build/lib/bytes/CMakeFiles/bytes.dir/DependInfo.cmake --color=
> make -s -f lib/tls_syntax/CMakeFiles/tls_syntax.dir/build.make lib/tls_syntax/CMakeFiles/tls_syntax.dir/build
> make -s -f lib/bytes/CMakeFiles/bytes.dir/build.make lib/bytes/CMakeFiles/bytes.dir/build
> /usr/bin/cmake -E cmake_echo_color --switch= --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=51,52 "Built target tls_syntax"
> /usr/bin/cmake -E cmake_echo_color --switch= --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=3,4 "Built target bytes"
> [  5%] Built target tls_syntax
> [  7%] Built target bytes
> CMakeFiles/Makefile2:351: update target 'lib/hpke/CMakeFiles/hpke.dir/all' due to: lib/bytes/CMakeFiles/bytes.dir/all
> make -s -f lib/hpke/CMakeFiles/hpke.dir/build.make lib/hpke/CMakeFiles/hpke.dir/depend
> CMakeFiles/Makefile2:434: update target 'lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/all' due to: lib/tls_syntax/CMakeFiles/tls_syntax.dir/all lib/bytes/CMakeFiles/bytes.dir/all
> make -s -f lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/build.make lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/depend
> lib/hpke/CMakeFiles/hpke.dir/build.make:251: target 'lib/hpke/CMakeFiles/hpke.dir/depend' does not exist
> cd /home/oceanfish81/mlspp/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/oceanfish81/mlspp /home/oceanfish81/mlspp/lib/hpke /home/oceanfish81/mlspp/build /home/oceanfish81/mlspp/build/lib/hpke /home/oceanfish81/mlspp/build/lib/hpke/CMakeFiles/hpke.dir/DependInfo.cmake --color=
> lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/build.make:133: target 'lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/depend' does not exist
> cd /home/oceanfish81/mlspp/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/oceanfish81/mlspp /home/oceanfish81/mlspp/lib/tls_syntax/test /home/oceanfish81/mlspp/build /home/oceanfish81/mlspp/build/lib/tls_syntax/test /home/oceanfish81/mlspp/build/lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/DependInfo.cmake --color=
> make -s -f lib/hpke/CMakeFiles/hpke.dir/build.make lib/hpke/CMakeFiles/hpke.dir/build
> make -s -f lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/build.make lib/tls_syntax/test/CMakeFiles/tls_syntax_test.dir/build
> lib/hpke/CMakeFiles/hpke.dir/build.make:81: update target 'lib/hpke/CMakeFiles/hpke.dir/src/aead_cipher.cpp.o' due to: ../lib/hpke/src/aead_cipher.cpp ../lib/bytes/include/bytes/bytes.h ../lib/hpke/include/hpke/hpke.h ../lib/hpke/src/aead_cipher.h ../lib/hpke/src/openssl_common.h lib/hpke/CMakeFiles/hpke.dir/flags.make
> /usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=5 "Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/aead_cipher.cpp.o"
> lib/hpke/CMakeFiles/hpke.dir/build.make:133: update target 'lib/hpke/CMakeFiles/hpke.dir/src/group.cpp.o' due to: ../lib/hpke/src/group.cpp ../lib/bytes/include/bytes/bytes.h ../lib/hpke/include/hpke/hpke.h ../lib/hpke/include/hpke/random.h ../lib/hpke/include/hpke/signature.h ../lib/hpke/src/common.h ../lib/hpke/src/group.h ../lib/hpke/src/openssl_common.h lib/hpke/CMakeFiles/hpke.dir/flags.make
> /usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=9 "Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/group.cpp.o"
> /usr/bin/cmake -E cmake_echo_color --switch= --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=53,54,55 "Built target tls_syntax_test"
> lib/hpke/CMakeFiles/hpke.dir/build.make:159: update target 'lib/hpke/CMakeFiles/hpke.dir/src/hpke.cpp.o' due to: ../lib/hpke/src/hpke.cpp ../lib/bytes/include/bytes/bytes.h ../lib/hpke/include/hpke/digest.h ../lib/hpke/include/hpke/hpke.h ../lib/hpke/include/hpke/signature.h ../lib/hpke/src/aead_cipher.h ../lib/hpke/src/common.h ../lib/hpke/src/dhkem.h ../lib/hpke/src/group.h ../lib/hpke/src/hkdf.h lib/hpke/CMakeFiles/hpke.dir/flags.make
> /usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=11 "Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/hpke.cpp.o"
> [  9%] Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/aead_cipher.cpp.o
> [ 10%] Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/group.cpp.o
> cd /home/oceanfish81/mlspp/build/lib/hpke && /usr/bin/clang++  -I/home/oceanfish81/mlspp/lib/hpke/include -I/home/oceanfish81/mlspp/lib/bytes/include -stdlib=libc++ -Wall -pedantic -Wextra -Werror -std=gnu++17 -o CMakeFiles/hpke.dir/src/aead_cipher.cpp.o -c /home/oceanfish81/mlspp/lib/hpke/src/aead_cipher.cpp
> [ 18%] Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/hpke.cpp.o
> [ 18%] Built target tls_syntax_test
> cd /home/oceanfish81/mlspp/build/lib/hpke && /usr/bin/clang++  -I/home/oceanfish81/mlspp/lib/hpke/include -I/home/oceanfish81/mlspp/lib/bytes/include -stdlib=libc++ -Wall -pedantic -Wextra -Werror -std=gnu++17 -o CMakeFiles/hpke.dir/src/group.cpp.o -c /home/oceanfish81/mlspp/lib/hpke/src/group.cpp
> cd /home/oceanfish81/mlspp/build/lib/hpke && /usr/bin/clang++  -I/home/oceanfish81/mlspp/lib/hpke/include -I/home/oceanfish81/mlspp/lib/bytes/include -stdlib=libc++ -Wall -pedantic -Wextra -Werror -std=gnu++17 -o CMakeFiles/hpke.dir/src/hpke.cpp.o -c /home/oceanfish81/mlspp/lib/hpke/src/hpke.cpp
> lib/hpke/CMakeFiles/hpke.dir/build.make:172: update target 'lib/hpke/CMakeFiles/hpke.dir/src/openssl_common.cpp.o' due to: ../lib/hpke/src/openssl_common.cpp ../lib/bytes/include/bytes/bytes.h ../lib/hpke/include/hpke/hpke.h ../lib/hpke/src/openssl_common.h lib/hpke/CMakeFiles/hpke.dir/flags.make
> /usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/oceanfish81/mlspp/build/CMakeFiles --progress-num=12 "Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/openssl_common.cpp.o"
> [ 20%] Building CXX object lib/hpke/CMakeFiles/hpke.dir/src/openssl_common.cpp.o
> cd /home/oceanfish81/mlspp/build/lib/hpke && /usr/bin/clang++  -I/home/oceanfish81/mlspp/lib/hpke/include -I/home/oceanfish81/mlspp/lib/bytes/include -stdlib=libc++ -Wall -pedantic -Wextra -Werror -std=gnu++17 -o CMakeFiles/hpke.dir/src/openssl_common.cpp.o -c /home/oceanfish81/mlspp/lib/hpke/src/openssl_common.cpp
> /home/oceanfish81/mlspp/lib/hpke/src/aead_cipher.cpp:102:14: error: use of undeclared identifier 'EVP_chacha20_poly1305'; did you mean 'EVP_aead_chacha20_poly1305'?
>       return EVP_chacha20_poly1305();
>              ^~~~~~~~~~~~~~~~~~~~~
>              EVP_aead_chacha20_poly1305
> /usr/local/include/openssl/evp.h:1273:17: note: 'EVP_aead_chacha20_poly1305' declared here
> const EVP_AEAD *EVP_aead_chacha20_poly1305(void);
>                 ^
> /home/oceanfish81/mlspp/lib/hpke/src/aead_cipher.cpp:102:14: error: cannot initialize return object of type 'const EVP_CIPHER *' (aka 'const evp_cipher_st *') with an rvalue of type 'const EVP_AEAD *' (aka 'const evp_aead_st *')
>       return EVP_chacha20_poly1305();
>              ^~~~~~~~~~~~~~~~~~~~~~~
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:119:14: error: use of undeclared identifier 'EVP_DigestSign'; did you mean 'EVP_DigestSignInit'?
>     if (1 != EVP_DigestSign(
>              ^~~~~~~~~~~~~~
>              EVP_DigestSignInit
> /usr/local/include/openssl/evp.h:627:5: note: 'EVP_DigestSignInit' declared here
> int EVP_DigestSignInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
>     ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:120:27: error: cannot initialize a parameter of type 'EVP_PKEY_CTX **' (aka 'evp_pkey_ctx_st **') with an rvalue of type 'std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>::value_type *' (aka 'unsigned char *')
>                ctx.get(), sig.data(), &siglen, data.data(), data.size())) {
>                           ^~~~~~~~~~
> /usr/local/include/openssl/evp.h:627:56: note: passing argument to parameter 'pctx' here
> int EVP_DigestSignInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
>                                                        ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:144:15: error: use of undeclared identifier 'EVP_DigestVerify'; did you mean 'EVP_DigestVerifyInit'?
>     auto rv = EVP_DigestVerify(
>               ^~~~~~~~~~~~~~~~
>               EVP_DigestVerifyInit
> /usr/local/include/openssl/evp.h:631:5: note: 'EVP_DigestVerifyInit' declared here
> int EVP_DigestVerifyInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
>     ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:145:18: error: cannot initialize a parameter of type 'EVP_PKEY_CTX **' (aka 'evp_pkey_ctx_st **') with an rvalue of type 'const std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>::value_type *' (aka 'const unsigned char *')
>       ctx.get(), sig.data(), sig.size(), data.data(), data.size());
>                  ^~~~~~~~~~
> /usr/local/include/openssl/evp.h:631:58: note: passing argument to parameter 'pctx' here
> int EVP_DigestVerifyInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
>                                                          ^
> 2 errors generated.
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:359:14: error: use of undeclared identifier 'EVP_PKEY_get_raw_public_key'
>     if (1 != EVP_PKEY_get_raw_public_key(rpk.pkey.get(), data_ptr, &data_len)) {
>              ^
> make[2]: *** [lib/hpke/CMakeFiles/hpke.dir/build.make:82: lib/hpke/CMakeFiles/hpke.dir/src/aead_cipher.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:369:7: error: use of undeclared identifier 'EVP_PKEY_new_raw_public_key'; did you mean 'EVP_PKEY_new_mac_key'?
>       EVP_PKEY_new_raw_public_key(evp_type, nullptr, enc.data(), enc.size());
>       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>       EVP_PKEY_new_mac_key
> /usr/local/include/openssl/evp.h:1150:11: note: 'EVP_PKEY_new_mac_key' declared here
> EVP_PKEY *EVP_PKEY_new_mac_key(int type, ENGINE *e, const unsigned char *key,
>           ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:384:9: error: use of undeclared identifier 'EVP_PKEY_get_raw_private_key'
>         EVP_PKEY_get_raw_private_key(rsk.pkey.get(), data_ptr, &data_len)) {
>         ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:395:7: error: use of undeclared identifier 'EVP_PKEY_new_raw_private_key'
>       EVP_PKEY_new_raw_private_key(evp_type, nullptr, skm.data(), skm.size());
>       ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:410:16: error: use of undeclared identifier 'EVP_PKEY_X25519'
>         return EVP_PKEY_X25519;
>                ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:412:16: error: use of undeclared identifier 'EVP_PKEY_X448'
>         return EVP_PKEY_X448;
>                ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:414:16: error: use of undeclared identifier 'EVP_PKEY_ED25519'
>         return EVP_PKEY_ED25519;
>                ^
> /home/oceanfish81/mlspp/lib/hpke/src/group.cpp:416:16: error: use of undeclared identifier 'EVP_PKEY_ED448'
>         return EVP_PKEY_ED448;
>                ^
> 12 errors generated.
> make[2]: *** [lib/hpke/CMakeFiles/hpke.dir/build.make:134: lib/hpke/CMakeFiles/hpke.dir/src/group.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:352: lib/hpke/CMakeFiles/hpke.dir/all] Error 2
> make: *** [Makefile:103: all] Error 2

> $ clang --version
> clang version 11.0.0 (https://github.com/llvm/llvm-project.git 0160ad802e899c2922bc9b29564080c22eb0908c)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> 

> $ cmake --version
> cmake version 3.18.2
> 

I was trying to build using/link against [libc++](https://libcxx.llvm.org/docs/) .

CC @pabuhler @bifurcation @fluffy 

Ivan

**Comment by bifurcation** [comment]
@advancedwebdeveloper Closing this as stale right now, feel free to re-file if there are still issues.
