### ISSUE TITLE
Cannot find doctest

### ISSUE THREAD

**Issue by ojroques** [cisco/mlspp#164]
Hello,

I'm on Ubuntu 18.04, I do have the required dependencies installed yet I cannot build the project following the README instructions.  I get this error:

```sh
cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug .
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at lib/bytes/test/CMakeLists.txt:4 (find_package):
  By not providing "Finddoctest.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "doctest", but
  CMake did not find one.

  Could not find a package configuration file provided by "doctest" with any
  of the following names:

    doctestConfig.cmake
    doctest-config.cmake

  Add the installation prefix of "doctest" to CMAKE_PREFIX_PATH or set
  "doctest_DIR" to a directory containing one of the above files.  If
  "doctest" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/olivier/Documents/mlspp/build/CMakeFiles/CMakeOutput.log".
Makefile:17: recipe for target 'build' failed
make: *** [build] Error 1
```

I've tried installing [doctest](https://github.com/onqtam/doctest) myself but simply placing `doctest.h` in the root folder or in `include/doctest/` or in any other place does not work. So is there a way to build the project without having to write a Finddoctest.cmake ourselves?

**Comment by dimarusyy** [comment]
Try to use vcpkg on your machine and configure using command:
`cmake -B build -DCMAKE_TOOLCHAIN_FILE=/mnt/d/dev/vcpkg/scripts/buildsystems/vcpkg.cmake .`
If you want to uses system dev packages, check that doctest cmake-files are installed.

**Comment by ojroques** [comment]
It works with vcpkg. Thank you :)
