### ISSUE TITLE
Using update proposals

### ISSUE THREAD

**Issue by emilmarstrander** [cisco/mlspp#357]
Hi,

I have been working with the mlspp build from December 2022. I then used the below code to update a node's key material. However, when I tried this on the build from 6.8.2023, it produces the following error: `Invalid proposal list` Is there another way of doing this in the newer build?

`proposal = session.update();`
`session.handle(proposal);`
`session.commit();`

**Comment by bifurcation** [comment]
This operation is illegal because it's a self-update.  If you want a node to update its own key, you can just call `session.commit()`, since committing produces a new leaf for the committer.
