### ISSUE TITLE
CI builds timing out on macOS

### ISSUE THREAD

**Issue by bifurcation** [cisco/mlspp#375]
For some reason, macOS CI builds are timing out intermittently, taking 5+ hours.  IIRC, things are hanging on the OpenSSL 3 build stage.  We should figure out why this is so that we can go back to requiring all-green for merge.

**Comment by bifurcation** [comment]
We have worked around this by running clang-tidy on Ubuntu.  We can reopen if it becomes an issue again.

**Comment by kgantchev** [comment]
Hi, sorry if I'm intruding, but a lot of people seem to be having issues with GitHub's macOS runners. Have you considered giving [FlyCI](https://flyci.net/?utm_source=github&utm_medium=community&utm_campaign=recommend) a try? It offers M2 runners for both public and private repos.
