### ISSUE TITLE
Is it production ready ?

### ISSUE THREAD

**Issue by dimarusyy** [cisco/mlspp#83]
Hi,
My team is considering to use MLS for group e2ee. 
Could you please say if this implementation is stable ? 
Is it used in production code ?

Thanks

**Comment by ozzyonez12** [comment]
Si

**Comment by dimarusyy** [comment]
Hope that means "yes" :)
TBH, I was expecting to get answer from maintainers as I see a bunch of commits every day.

**Comment by bifurcation** [comment]
@dimarusyy - I would say not quite yet.  The [MLS specification](https://messaginglayersecurity.rocks/) is still being finalized, so this library will change to keep up.
